/* eslint-disable */
/**
 * Generated `api` utility.
 * THIS FILE IS GENERATED BY CONVEX. DO NOT EDIT.
 * Run `npx convex dev` to regenerate.
 */
import { anyApi } from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export const api: any = anyApi;
export const internal: any = anyApi;
