/* eslint-disable */
/**
 * Generated data model types.
 * THIS FILE IS GENERATED BY CONVEX. DO NOT EDIT.
 * Run `npx convex dev` to regenerate.
 */
import { defineSchema } from "convex/server";
import { GenericId } from "convex/values";

export type TableNames =
  | "users"
  | "groups"
  | "groupMembers"
  | "workouts"
  | "weeklyScores"
  | "weeklyNarratives"
  | "reactions"
  | "weeklyGameplans";

export type Id<TableName extends TableNames> = GenericId<TableName>;

export type Document<TableName extends TableNames> =
  TableName extends "users" ? {
    _id: Id<"users">;
    _creationTime: number;
    clerkId: string;
    name: string;
    email?: string;
    avatarUrl?: string;
    stravaConnected: boolean;
    garminConnected: boolean;
    appleHealthConnected: boolean;
    stravaAccessToken?: string;
    stravaRefreshToken?: string;
    stravaTokenExpiresAt?: number;
    stravaAthleteId?: number;
    fitnessLevel: "beginner" | "intermediate" | "advanced";
    typicalActivities: string[];
    avgWeeklyWorkouts: number;
    currentStreak: number;
    longestStreak: number;
    subscriptionStatus: "trial" | "active" | "expired" | "none";
    subscriptionExpiresAt?: number;
    stripeCustomerId?: string;
    stripeSubscriptionId?: string;
    trialStartedAt?: number;
    createdAt: number;
  } :
  TableName extends "groups" ? {
    _id: Id<"groups">;
    _creationTime: number;
    name: string;
    emoji?: string;
    ownerId: Id<"users">;
    inviteCode: string;
    weeklyStakes?: string;
    memberCount: number;
    createdAt: number;
  } :
  TableName extends "workouts" ? {
    _id: Id<"workouts">;
    _creationTime: number;
    userId: Id<"users">;
    source: "strava" | "garmin" | "apple_health" | "manual";
    externalId?: string;
    activityType: string;
    durationMinutes: number;
    distanceKm?: number;
    avgHeartRate?: number;
    maxHeartRate?: number;
    elevationGainM?: number;
    calories?: number;
    rpeSelfReported?: number;
    userNote?: string;
    photoUrl?: string;
    startedAt: number;
    effortScore: number;
    aiReasoning: string;
    aiSummary: string;
    intensityScore: number;
    durationScore: number;
    consistencyBonus: number;
    personalEffortScore: number;
    weekId: string;
    scored: boolean;
    createdAt: number;
  } :
  Record<string, any>;

export type DataModel = {
  [TableName in TableNames]: {
    document: Document<TableName>;
    fieldPaths: string;
    indexes: {};
    searchIndexes: {};
    vectorIndexes: {};
  };
};
